base: 'https://sitepackageone.ddev.site/'
dependencies:
  - typo3/fluid-styled-content
  - typo3/form
  - typo3/felogin
  - typo3/seo-sitemap
errorHandling:
  -
    errorCode: 404
    errorHandler: Page
    errorContentSource: 't3://page?uid=11'
  -
    errorCode: 403
    errorHandler: Page
    errorContentSource: 't3://page?uid=12'
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    locale: en_US.UTF-8
    navigationTitle: English
    flag: us
    hreflang: ''
    websiteTitle: ''
rootPageId: 1
websiteTitle: SitePackageOne
